kind: ClusterDeployment
metadata:
  name: cluster-deployment
spec:
  config:
    controlPlaneNumber: 1
    workersNumber: 2
    location: "westus"
    subscriptionID: "d8c00bed-c0a8-4ae2-ba65-dbd7fe1c5139"
    controlPlane:
      vmSize: Standard_A4_v2
    worker:
      vmSize: Standard_A4_v2
    clusterIdentity:
      name: "" # change it
      namespace: "" # change it
