resources:
  - ../../../../../../base/k0rdent/templates/services
patches:
  - path: service-template-patch.yaml
    target:
      kind: ServiceTemplate
  - path: name-patch.yaml
    target:
      kind: ServiceTemplate
  - path: name-patch.yaml
    target:
      kind: ServiceTemplateChain
replacements:
  - source:
      kind: ServiceTemplate
      fieldPath: metadata.name
    targets:
      - select:
          kind: ServiceTemplateChain
        fieldPaths:
          - spec.supportedTemplates.[name=service-template].name
