nameSuffix: -cloud-1
resources:
  - openstack-credentials-secret.yaml
  - ../../../../../../base/k0rdent/credentials/openstack
replacements:
  - source:
      kind: SealedSecret
      fieldPath: spec.template.metadata.name
    targets:
      - select:
          kind: Credential
        fieldPaths:
          - spec.identityRef.name
  - source:
      kind: SealedSecret
      fieldPath: spec.template.metadata.namespace
    targets:
      - select:
          kind: Credential
        fieldPaths:
          - spec.identityRef.namespace
