resources:
  - configuration
  - cluster-deployments
  - templates
  - credentials
  - multiclusterservices
patches:

  ### AccessManagement ###
  - target:
      kind: AccessManagement
    patch: |-
      - op: add
        path: /spec/accessRules/-
        value:
          targetNamespaces:
            list:
              - cluster-management
          credentials:
            - aws-credential-cloud-1
          clusterTemplateChains:
            - custom-aws-standalone-cp-0-0-1
            - custom-aws-standalone-cp-0-0-2
          serviceTemplateChains:
            - custom-ingress-nginx-4-11-0
            - custom-ingress-nginx-4-11-3

  ### MultiClusterService ###
  # Global kyverno 3.2.6
  - path: templates/services/custom-kyverno-3-2-6/service-spec-patch.yaml
    target:
      kind: MultiClusterService
      name: protected-kyverno
  - path: templates/services/custom-kyverno-3-2-6/cluster-selector-label-patch.yaml
    target:
      kind: MultiClusterService
      name: protected-kyverno
  - path: templates/services/custom-kyverno-3-2-6/labels-patch.yaml
    target:
      kind: ClusterDeployment
  - path: multiclusterservices/protected-kyverno/labels-patch.yaml
    target:
      kind: ClusterDeployment

  ### AWS ###
  # Cluster aws-production-1
  - path: templates/clusters/aws/custom-aws-standalone-cp-0-0-1/cluster-deployment-patch.yaml
    target:
      kind: ClusterDeployment
      name: aws-production-1
  - path: credentials/aws/aws-cloud-1/cluster-deployment-patch.yaml
    target:
      kind: ClusterDeployment
      name: aws-production-1
  - path: templates/services/custom-ingress-nginx-4-11-0/service-spec-patch.yaml
    target:
      kind: ClusterDeployment
      name: aws-production-1
  
  # Cluster aws-managed-cluster-1
  - path: templates/clusters/aws/custom-aws-standalone-cp-0-0-2/cluster-deployment-patch.yaml
    target:
      kind: ClusterDeployment
      name: aws-managed-cluster-1
  - path: credentials/aws/aws-cloud-1/cluster-deployment-patch.yaml
    target:
      kind: ClusterDeployment
      name: aws-managed-cluster-1
  - path: templates/services/custom-ingress-nginx-4-11-0/service-spec-patch.yaml
    target:
      kind: ClusterDeployment
      name: aws-managed-cluster-1
  
  # Cluster aws-managed-cluster-2
  - path: templates/services/custom-ingress-nginx-4-11-3/service-spec-patch.yaml
    target:
      kind: ClusterDeployment
      name: aws-managed-cluster-2
  - path: templates/clusters/aws/custom-aws-standalone-cp-0-0-1/cluster-deployment-patch.yaml
    target:
      kind: ClusterDeployment
      name: aws-managed-cluster-2
  - path: credentials/aws/aws-cloud-2/cluster-deployment-patch.yaml
    target:
      kind: ClusterDeployment
      name: aws-managed-cluster-2  

  ### Azure ###
  # Cluster azure-managed-cluster-1
  - path: templates/clusters/azure/custom-azure-standalone-cp-0-0-1/cluster-deployment-patch.yaml
    target:
      kind: ClusterDeployment
      name: azure-managed-cluster-1
  - path: credentials/azure/azure-cloud-1/cluster-deployment-patch.yaml
    target:
      kind: ClusterDeployment
      name: azure-managed-cluster-1

replacements:
  ### Azure ###
  # Cluster azure-managed-cluster-1
  - source:
      kind: AzureClusterIdentity
      name: azure-cluster-identity-cloud-1
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ClusterDeployment
          name: azure-managed-cluster-1
        fieldPaths:
          - spec.config.clusterIdentity.namespace
