---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./management-clusters/management-cluster-1/components/helm-repo
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
    namespace: flux-system
